name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: attempt to use cs2cpp package
      run:
        |
        python3 -m pip install cs2cpp
        python3 -c 'from cs2cpp import CSharpToCpp; print (CSharpToCpp(useRegex=True).Transform(""))'
        python3 -c 'import retranslator, cs2cpp; retranslator.TranslatorCLI(args=["test.cs"], translator=cs2cpp.CSharpToCpp, extension=".cpp").run()'
        
