name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: attempt to use cs2cpp package
      run:
        |
        pip install --upgrade cs2cpp
        python -c 'from cs2cpp import CSharpToCpp; print (CSharpToCpp().Transform(""))'
